### ISSUE TITLE
.

### ISSUE THREAD

**Issue by darkx09092003** [JeffersonRPM/Landing-page-anime#4]
.

**Comment by JeffersonRPM** [comment]
Yes you can, feel free!
If you can create a fork :)
________________________________
De: darkx09092003 ***@***.***>
Enviado: quarta-feira, 14 de junho de 2023 04:11
Para: JeffersonRPM/Landing-page-anime ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [JeffersonRPM/Landing-page-anime] Sorry buddy please (Issue #4)


Buddy can I use this please you are very good can I use this please 🙏
